// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function ApplyTemplateVariables(arg1:string,arg2:models.Recipient):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetRecipients():Promise<Array<models.Recipient>>;

export function GetSettings():Promise<models.SettingsResponse>;

export function GetSignatures():Promise<Array<models.Signature>>;

export function GetTemplates():Promise<Array<models.Template>>;

export function GetVersion():Promise<Record<string, string>>;

export function MatchRecipientByFileName(arg1:string,arg2:Array<models.Recipient>):Promise<models.Recipient>;

export function MatchTemplateByFileName(arg1:string,arg2:Array<models.Template>):Promise<models.Template>;

export function OpenFileDialog():Promise<Array<models.Attachment>>;

export function ReadFileAsAttachment(arg1:string):Promise<models.Attachment>;

export function ReadFilesAsAttachments(arg1:Array<string>):Promise<Array<models.Attachment>>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveConfigWithAuth(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendMail(arg1:string,arg2:string,arg3:string,arg4:Array<models.Attachment>):Promise<models.SendMailResponse>;

export function TestConnection():Promise<models.ConnectionTestResponse>;

export function ValidateSendSafety(arg1:models.Recipient,arg2:Array<models.Attachment>,arg3:string):Promise<Array<string>>;
