// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplateVariables(arg1, arg2) {
  return window['go']['main']['App']['ApplyTemplateVariables'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecipients() {
  return window['go']['main']['App']['GetRecipients']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSignatures() {
  return window['go']['main']['App']['GetSignatures']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function MatchRecipientByFileName(arg1, arg2) {
  return window['go']['main']['App']['MatchRecipientByFileName'](arg1, arg2);
}

export function MatchTemplateByFileName(arg1, arg2) {
  return window['go']['main']['App']['MatchTemplateByFileName'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFileAsAttachment(arg1) {
  return window['go']['main']['App']['ReadFileAsAttachment'](arg1);
}

export function ReadFilesAsAttachments(arg1) {
  return window['go']['main']['App']['ReadFilesAsAttachments'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveConfigWithAuth(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfigWithAuth'](arg1, arg2, arg3, arg4);
}

export function SaveTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2, arg3, arg4);
}

export function SendMail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMail'](arg1, arg2, arg3, arg4);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function ValidateSendSafety(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateSendSafety'](arg1, arg2, arg3);
}
